/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finalprojectpokedex;

import com.formdev.flatlaf.FlatLightLaf;
import com.github.oscar0812.pokeapi.models.pokemon.Pokemon;
import java.awt.BorderLayout;
import javax.swing.JTabbedPane;

/**
 *
 * @author Cameron
 */
public class PokedexIntro extends javax.swing.JFrame {

    /**
     * Creates new form PokedexIntro
     */
    public PokedexIntro() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(217, 76, 56)); // Set the background color of the content pane
        setTitle("Pokédex Application");
        setResizable(false); // Non-resizable window
        setLocationRelativeTo(null); // Center window
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        pokedexNameLabel = new javax.swing.JLabel();
        pokedexEnterButton = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pokedexNameLabel.setFont(new java.awt.Font("Pokemon Solid", 0, 26)); // NOI18N
        pokedexNameLabel.setText(" Cam's Pokédex and Pokémon Quiz!");
        pokedexNameLabel.setMaximumSize(new java.awt.Dimension(203, 17));
        pokedexNameLabel.setMinimumSize(new java.awt.Dimension(203, 170));

        pokedexEnterButton.setFont(new java.awt.Font("Pokemon Solid", 0, 24)); // NOI18N
        pokedexEnterButton.setText("Enter Pokédex");
        pokedexEnterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pokedexEnterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pokedexEnterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(pokedexNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(pokedexNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(pokedexEnterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void pokedexEnterButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // Main tabbed pane
        JTabbedPane tabbedPane = new JTabbedPane();

        // Instances of the panels
        PokedexGUI pokedexPanel = new PokedexGUI();
        PokemonQuiz quizPanel = new PokemonQuiz();
        
        // Adds the panels to the tabbed pane
        tabbedPane.addTab("Pokédex", pokedexPanel);
        tabbedPane.addTab("Quiz", quizPanel);

        getContentPane().removeAll();
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(tabbedPane, BorderLayout.CENTER);
        revalidate();
        repaint();
    }                                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PokedexIntro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PokedexIntro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PokedexIntro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PokedexIntro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 FlatLightLaf.setup();
                new PokedexIntro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JButton pokedexEnterButton;
    private javax.swing.JLabel pokedexNameLabel;
    // End of variables declaration                   

}
